name: Pre commit

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  download_data:
    name: Pre commit
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        name: Install Python 3.8
        with:
          python-version: '3.8'
      - name: install tools
        run: python -m pip install pre-commit
      - name: run pre-commit
        run: pre-commit run --all --show-diff-on-failure
